name: Allfeat CI

on:
  push:
    branches:
      - master
      - add-ci-for-format-checker
  pull_request:
    branches:
      - master

jobs:
  check-format:
    name: Check code format
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Check format
        run: cargo fmt --check --all
